apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchbase-ha
spec:
  serviceName: "couchbase-ha"
  replicas: 1
  selector:
    matchLabels:
        app: couchbase-ha
  template:
    metadata:
      labels:
        app: couchbase-ha
    spec:
      containers:
      - name: couchbase-ha
        image: {BUILT_IMAGE_NAME}:{TAG}
        imagePullPolicy: Always        
        ports:
        - containerPort: 8091
        - containerPort: 8092
        - containerPort: 8093
        - containerPort: 8094
        - containerPort: 11210
        volumeMounts:
        - name: couchbase-ha-data
          mountPath: /opt/couchbase/var
        env:
          - name: MASTER_NODE
            value: "couchbase-ha-0"
          - name: SERVICE_NAME
            value: "couchbase-ha"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace                       
        envFrom:
          - secretRef:
              name: couchbase-ha-secrets  
          - configMapRef:
              name: couchbase-ha-configs                      
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "/opt/couchbase/configure-node-latest.sh"]
  volumeClaimTemplates:
  - metadata:
      name: couchbase-ha-data
      annotations:
        volume.beta.kubernetes.io/storage-class: "nfs-client"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi

---

apiVersion: v1
kind: Service
metadata:
  name: couchbase-ha
  labels:
    app: couchbase-ha
spec:
  ports:
  - name: admin
    port: 8091
  - name: views
    port: 8092
  - name: query
    port: 8093
  - name: more
    port: 8094
  - name: memcached
    port: 11210
  clusterIP: None
  selector:
    app: couchbase-ha
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-ha-service
  labels:
    app: couchbase-ha-service
spec:
  ports:
    - name: admin
      port: 8091
    - name: views
      port: 8092
    - name: query
      port: 8093
    - name: more
      port: 8094
    - name: memcached
      port: 11210
  selector:
    app: couchbase-ha
  type: ClusterIP
