apiVersion: v1
kind: Service
metadata:
  name: couchbase-ha
  labels:
    app: couchbase-ha
spec:
  ports:
  - name: admin
    port: 8091
  - name: views
    port: 8092
  - name: query
    port: 8093
  - name: more
    port: 8094
  - name: memcached
    port: 11210
  clusterIP: None
  selector:
    app: couchbase-ha
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-ha-service
  labels:
    app: couchbase-ha-service
spec:
  ports:
    - name: admin
      port: 8091
    - name: views
      port: 8092
    - name: query
      port: 8093
    - name: more
      port: 8094
    - name: memcached
      port: 11210
  selector:
    app: couchbase-ha
  type: ClusterIP
